modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="bemysword"
version="1.0.0"
displayName="Ck7 - Be My Sword"
description='''
        Adds human guardians that can be tamed, leveled up, and equipped.
        They will follow and protect you across your world.
    '''

[[dependencies.bemysword]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.bemysword]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"